export const teamDefaultValue = {
  // team_id_: 123123123,
  team_name_: "",
  address_: "",
  location_accuracy_: "High",
  templates_id_: [],
};

export const managerDefaultValue = {
  // manager_id: 1044463,
  first_name_: "",
  last_name_: "",
  email_: "",
  phone_: "",
  form_user_id_: [],
  teams_: [],
  template_id_: [],
  role_manager_id_: "",
  password_: "",
  blocked: 0,

  // DEFAULT VALUES FOR MANAGER
  edit_fleet_wallet: 0,
  edit_status: 1,
  edit_task: 1,
  last_login_datetime: "2021-11-02T15:54:38.000Z",
  create_driver: 1,
  create_task: 1,
  create_team: 0,
  read_default_team_tasks: 1,
  update_notification: 0,
  username: "James Calas",
  view_auto_allocation: 1,
  view_notification: 0,
  view_status: 1,
  view_task: 1,
};

export const agentDefaultValue = {
  email_: "",
  first_name_: "",
  last_name_: "",
  username_: "",
  phone_: "",
  password_: "",
  tags_: [],
  // ASSIGNED TO TEAM
  team_id_: [],
  role_id_: "",
  address_: "",
  geofence_id_: [],

  transport_type_: "",
  transport_desc_: "",
  template_id_: [],
  color_: "",

  signup_verification_: 0, // CHECKBOX

  //AGENT ID
  // fleet_id_: 1050762,
  fleet_image_: "",
  license_: "",

  status_: 1,

  // USE FOR BLOCK
  is_active: 1,
  // DEFAULT VALUES FOR AGENT
  battery_level: 64,
  block_reason: "None",
  device_type: 3352,
  fleet_thumb_image:
    "https://tookan.s3.amazonaws.com/fleet_thumb_profile/user.png",
  fleet_type: 1,
  has_gps_accuracy: 1,
  is_available: 1,
  latitude: "18.4083838",
  login_id: "asalguero",
  longitude: "-66.1596594",
  registration_status: 1,
  timezone: "300",
  total_rated_tasks: 2,
  total_rating: 10,
};

export const customerDefaultValue = {
  // CUSTOMER ID
  // customer_id: 41712636,
  is_form_user_: false,
  form_user_id_: [],
  company_: "",
  creation_datetime_: "",
  customer_address_: "",
  customer_email_: "",
  customer_latitude_: 10,
  customer_longitude_: 106,
  customer_phone_: "",
  customer_username_: "",
  description_: "",
  password_: "",
  tags_: [],

  // DEFAULT VALUES FOR CUSTOMER
  access_token: "08383ec0a9445e441c162c3d1d15234e1de7c5fb28",
  user_id: 1007545,
  is_active: 1,
  avg_rating: 0,
  rated_task_count: 0,
  vendor_id: "None",
  password_reset_token: "None",
  is_blocked: 0,
  vendor_image: "None",
  device_type: "None",
  device_token: "None",
  app_versioncode: "None",
  app_access_token: "None",
  language: "None",
  last_login_date_time: "2021-07-09T16:23:33.000Z",
  vendor_api_key: "None",
  fb_token: "None",
  otp: "None",
  is_phone_verified: 0,
  credits: 0,
  pending_amount: 0,
  successful_task_count: 0,
  referral_code: "None",
  referrer_id: "None",
  is_first_login: 1,
  registration_status: 2,
  paytm_enabled: "None",
  unverified_phone: "None",
  favorite_fleets: "None",
  phone_no: "+17874391474",
  authentic_phone_no: "+17874391474",
  reference_id: "None",
  updation_datetime: "2021-07-09T16:23:33.000Z",
  Registration_Status: "-",
};

export const taskDefaultValue = {
  // "job_id":"", // TASK ID
  // job_id: "",
  job_description_attachment_: [],
  customer_id_: "",
  order_id_: "",
  started_datetime_: "",
  completed_datetime_: "",
  team_id_: "", //"1323866",
  template_id_: "",
  job_status_: 2,
  job_description_: "",
  agents_id: [],
  fleet_id_: "None", // SELECTED AGENT ID
  // DEFAULT VALUES
  fleet_name_: "",
  fleet_latitude: "18.19791334376984",
  fleet_longitude: "-65.71787811533424",
  fleet_image: "https://files.trgflex.com/fleet_profile/user.png",
  job_pickup_name: "",
  job_pickup_phone: "",
  user_id: 1007545,
  timezone: "300",
  has_pickup: 0,
  pickup_delivery_relationship: "442102060433016627254235332004",
  completed_by_admin: 0,
  job_pickup_datetime: "2022-09-09 08:25:00",

  job_delivery_datetime: "2022-09-09 08:55:00",
  job_type: 2,
  creation_datetime: "2022-09-09 12:10:23",
  customer_comment: "None",
  job_pickup_latitude: "18.14213471488854",
  job_pickup_longitude: "-65.80711657187511",
  job_pickup_address: "350 C. Dr. Vidal, Humacao, 00791, Puerto Rico",
  days_started: "11",
  acknowledged_datetime: "2022-09-09T12:10:28.000Z",
  arrived_datetime: "2022-09-09T21:10:50.000Z",
  total_distance_travelled: 16171,
  fleet_rating: 0,
};
